### ISSUE TITLE
python version issue (may be user error)

### ISSUE THREAD

**Issue by conta877** [dwavesystems/dwave-neal#47]
**Description**

Works on python 2.7, getting the following error on 3

-------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-60-ce67a2e0044c> in <module>()
      4 h = {0:1.0,1:1.0}
      5 J = {(0,1):2.0}
----> 6 logical_sa_solutions = sa_sampler.sample_ising(h,J)

/opt/conda/lib/python3.6/site-packages/dimod/core/sampler.py in sample_ising(self, h, J, **parameters)
    202         """
    203         bqm = BinaryQuadraticModel.from_ising(h, J)
--> 204         response = self.sample(bqm, **parameters)
    205         return response
    206 

/opt/conda/lib/python3.6/site-packages/dimod/decorators.py in _index_label(sampler, bqm, **kwargs)
     44         # if already index-labelled, just continue
     45         if all(v in linear for v in range(len(bqm))):
---> 46             return f(sampler, bqm, **kwargs)
     47 
     48         try:

/opt/conda/lib/python3.6/site-packages/neal/sampler.py in sample(self, bqm, beta_range, num_reads, sweeps, beta_schedule_type, seed)
    228                                                 seed)
    229         off = bqm.spin.offset
--> 230         response = dimod.Response.from_matrix(samples, {'energy': [en + off for en in energies]}, vartype=dimod.SPIN)
    231 
    232         return response.change_vartype(bqm.vartype, inplace=True)

AttributeError: type object 'Response' has no attribute 'from_matrix'

**To Reproduce**

h = {0:1.0,1:1.0}
J = {(0,1):2.0}
logical_sa_solutions = sa_sampler.sample_ising(h,J)

**Environment:**
 - OS: Ubuntu 16.04
 - Python version: 3.6

**Comment by conta877** [comment]
yup... didn't upgrade.
